### ISSUE TITLE
Friendly IdP menu labels doesn't work

### ISSUE THREAD

**Issue by joe-hutchinson-cko** [okta/okta-aws-cli#102]
Recently released https://github.com/okta/okta-aws-cli#friendly-idp-menu-labels seems to be broken. I've set the okta.yaml file in the designated directory but friendly names are still not displayed instead you continue to see the account numbers.

Using version 1.0.0.

**Comment by joshgch** [comment]
I'm having the same issue, I built out my `okta.yaml` exactly as shown in the example but it isn't showing friendly names at all. In my case I do not have multiple AWS Federation apps, instead, I have just one, but it has dozens of different accounts. 

Side note, it would also be super helpful for my organization if we could have friendly names for the role ARNs as well.

**Comment by monde** [comment]
@joe-hutchinson-cko are you 100% sure your `$HOME/.okta/okta.yaml` is formatted like the example and your https://github.com/okta/okta-aws-cli#example-homeoktaoktayaml and your ARN values are exactly those of our various AWS Fed apps in the Okta Admin UI panel.

@joshgch I'd like to set up a zoom and get a demo from you about your use case. Can you open a support case https://support.okta.com/help/s/?language=en_US and reference this comment? Then our support engineer can share your contact information with me and I'll set up the zoom. Thanks

**Comment by alisoleimani** [comment]
@joshgch @monde I am facing the same issue. how you managed to solve it?

**Comment by eberens-nydig** [comment]
Hitting the same issue using `1.0.2`. All appears to be in order running `--debug-config` but yet I do not get friendly labels.

```
➜  ~ okta-aws-cli --debug-config
Given example okta.yaml for reference:

---
awscli:
  idps:
    "arn:aws:iam::123456789012:saml-provider/company-okta-idp": "Data Production"
    "arn:aws:iam::012345678901:saml-provider/company-okta-idp": "Data Development"
	
found home directory "/Users/user.name"
okta.yaml is readable "/Users/user.name/.okta/okta.yaml"
okta.yaml is valid yaml
okta.yaml has root "awscli" section
okta.yaml "awscli.idps" section is a map of 11 ARN string keys to friendly string label values
okta.yaml is OK
debugging okta-aws-cli config $HOME/.okta/okta.yaml is complete
➜  ~ okta-aws-cli -v            
okta-aws-cli version 1.0.2
➜  ~ okta-aws-cli   
System web browser will open the following URL to begin Okta device authorization for the AWS CLI

https://XXXX.okta.com/activate?user_code=XXXXXX

? Choose an IdP:  [Use arrows to move, type to filter]
> arn:aws:iam::XXXX:saml-provider/XXXX.okta.com
  arn:aws:iam::XXXX:saml-provider/XXXX.okta.com
  arn:aws:iam::XXXX:saml-provider/XXXX.okta.com
  arn:aws:iam::XXXX:saml-provider/XXXX.okta.com
  arn:aws:iam::XXXX:saml-provider/XXXX.okta.com
  arn:aws:iam::XXXX:saml-provider/XXXX.okta.com
  arn:aws:iam::XXXX:saml-provider/XXXX.okta.com
```

**Comment by monde** [comment]
hey everyone, I see you found the `okta-aws-cli --debug-config` operation https://github.com/okta/okta-aws-cli#debug-oktayaml but the CLI is still having some sort of issue with using the okta.yaml for setting up friendly IDP menus.

I'll add in an `--debug` flag in the next release that is separate from what `--debug-config` and `--debug-api` currently perform. `--debug` will the generic way we can surface what the CLI is performing during its run.

So, in this case, it might look something like:


```
$ okta-aws-cli --oidc-client-id abc --org-domain test-org.okta.com --open-browser --debug

System web browser will open the following URL to begin Okta device authorization for the AWS CLI

https://test-org.okta.com/activate?user_code=HWFMVWND

  found IdP ARN "arn:aws:iam::1234:saml-provider/s3" having friendly label "S3 IdP"
  did not find friendly label for IdP ARN
    "arn:aws:iam::1234:saml-provider/ec2"
    in okta.yaml awscli.idps map:
      "arn:aws:iam::1234:saml-provider/eks": "EKS IdP"
      "arn:aws:iam::1234:saml-provider/cloudfront": "CloudFront IdP"
      "arn:aws:iam::1234:saml-provider/s3": "S3 IdP"
  found IdP ARN "arn:aws:iam::1234:saml-provider/eks" having friendly label "EKS IdP"
  found IdP ARN "arn:aws:iam::1234:saml-provider/cloudfront" having friendly label "CloudFront IdP"
? Choose an IdP:  [Use arrows to move, type to filter]
> S3 IdP
  AWS Account Federation (EC2) (arn:aws:iam::1234:saml-provider/ec2)
  EKS IdP
  CloudFront IdP
```

what do you think @kenhen93Evolve @eberens-nydig ?

**Comment by kenhen93Evolve** [comment]
@monde That sounds great! When is the next release? I am trying to roll out using this cli to my company ASAP.

**Comment by monde** [comment]
I released [v1.1.0](https://github.com/okta/okta-aws-cli/releases/tag/v1.1.0) yesterday and it's listed in homebrew.  @kenhen93Evolve @eberens-nydig can you install v1.1.0, run your okta-aws-cli command as you'll normally work but add `--debug` to your command flags? It will list live information about look ups in your okta.yaml that I described above. Let me know what you find.

**Comment by kenhen93Evolve** [comment]
@monde Debug is not working for me.

% okta-aws-cli --version
okta-aws-cli version 1.1.0

% okta-aws-cli --debug --org-domain sample.oktapreview.com --oidc-client-id 9999999999999 --aws-acct-fed-app-id 9999999999 --write-aws-credentials --cache-access-token --open-browser --session-duration "14400"
System web browser will open the following URL to begin Okta device authorization for the AWS CLI

https://sample.oktapreview.com/activate?user_code=GGHDGHG

? Choose an IdP: arn:aws:iam::000000000000:saml-provider/okta
? Choose a Role: arn:aws:iam::000000000000:role/power_user
Updated profile "default" in credentials file "/Users/user/.aws/credentials".

**Comment by kenhen93Evolve** [comment]
@monde do you have an update? I would really like to get this working.

**Comment by monde** [comment]
@kenhen93Evolve the feature is for friendly IdP labels, you are running okta-aws-cli with oidc client id and the aws account fed id so you'd never hit friendly IdP labels. I'll have to see about extending the feature to include friendly role labels as well.

**Comment by kenhen93Evolve** [comment]
OK thank you

**Comment by kenhen93Evolve** [comment]
This seems to weird to me that it would not work with Federated AWS. I would appreciate if this feature could be high priority as my developers are going to have to remember account numbers now.

If there is another solution you would recommend @monde , please let me know. Thank you.

**Comment by monde** [comment]
@kenhen93Evolve I just have to make time to finish that. The features on this project have been entirely incremental from its base MVP which was originally more of a POC. The pressing request from the community was to get friendly IdP labels, in hindsight I should have thrown in friendly labels for roles as well.

**Comment by kenhen93Evolve** [comment]
OK Thank you. Please let me know

**Comment by DawoodAbbasAli** [comment]
@monde , can you please provide an ETA for this fix.  It is very important for us.

**Comment by monde** [comment]
@DawoodAbbasAli what aspect isn't working for you? A number of adjustments have been released https://github.com/okta/okta-aws-cli/releases/tag/v1.1.0 . You can run your command as you normally would with the `--debug` flag and additional diagnostic information about ARNs, IdP labels, and the okta.yaml are printed out.

**Comment by DawoodAbbasAli** [comment]
I am unable to see the friendly labels added in okta.yaml.  This is the command:
`okta-aws-cli --org-domain ${OKTA_ORG_DOMAIN} --oidc-client-id ${OKTA_OIDC_CLIENT_ID} --aws-acct-fed-app-id ${AWS_FED_APP_ID} --write-aws-credentials --open-browser --session-duration=28800"`

This is my OKTA yaml:
dawoodabas@MT-C02D1DE8MD6M kt % cat $HOME/.okta/okta.yaml 
```
---
awscli:
 idps:
  "arn:aws:iam::XXXXXXXXXXXX:saml-provider/okta-identity-engine": "Playground"   
  "arn:aws:iam::XXXXXXXXXXXX:saml-provider/okta-identity-engine": "Test"
```

**Comment by monde** [comment]
@DawoodAbbasAli as I said, if you run your command with the `--debug` flag it will give diagnostics about your okta.yaml file and if it can look up IdP labels from with ARNs from your AWS Fed App. Let me know what that diagnostic is saying if it's not apparent to you. This is in the latest v1.1.0 https://github.com/okta/okta-aws-cli/releases/tag/v1.1.0 that is also available in homebrew.

Also, there is stand alone diagnostic `--debug-config` where okta-aws-cli will inspect your okta.yaml, print out diagnostics, and exit.

**Comment by DawoodAbbasAli** [comment]
@monde , i have tried the 1.1.0 version with the --debug flag , and seeing this:
```
System web browser will open the following URL to begin Okta device authorization for the AWS CLI

https://oie-XXXX.oktapreview.com/activate?user_code=XXXXXXX

? Choose an IdP:  [Use arrows to move, type to filter]
> arn:aws:iam:: XXXXXXXXXXXX:saml-provider/okta-identity-engine
  arn:aws:iam:: XXXXXXXXXXXX:saml-provider/okta-identity-engine
```

This is the output of ----debug-config flag

dawoodabas@MT-C02D1DE8MD6M kt % ./okta-aws-cli_v1.1.0 --debug-config
Given example okta.yaml for reference:

```
dawoodabas@MT-C02D1DE8MD6M kt % ./okta-aws-cli_v1.1.0 --debug-config
Given example okta.yaml for reference:

---
awscli:
  idps:
    "arn:aws:iam::123456789012:saml-provider/company-okta-idp": "Data Production"
    "arn:aws:iam::012345678901:saml-provider/company-okta-idp": "Data Development"
	
found home directory "/Users/dawoodabas"
okta.yaml is readable "/Users/dawoodabas/.okta/okta.yaml"
okta.yaml is valid yaml
okta.yaml has root "awscli" section
okta.yaml "awscli.idps" section is a map of 2 ARN string keys to friendly string label values
okta.yaml is OK
debugging okta-aws-cli config $HOME/.okta/okta.yaml is complete
```

**Comment by kenhen93Evolve** [comment]
@DawoodAbbasAli I think you are running into the same issue as I am. The okta-aws-cli's friendly labels are not coded up yet for oidc client id and the aws account fed id

**Comment by monde** [comment]
Thanks @kenhen93Evolve @DawoodAbbasAli I'm trying to carve some additional time to also allow for setting friendly Role labels. I'll keep you posted.

**Comment by JohnPaton** [comment]
Just popping in to say that I'm also affected by this. I assume it's related to what you are saying about federation, but as a simple user it's not totally clear to me. 

```console
$ okta-aws-cli --version
okta-aws-cli version 1.1.0

$ okta-aws-cli --debug-config
Given example okta.yaml for reference:

---
awscli:
  idps:
    "arn:aws:iam::123456789012:saml-provider/company-okta-idp": "Data Production"
    "arn:aws:iam::012345678901:saml-provider/company-okta-idp": "Data Development"

found home directory "/Users/jpaton"
okta.yaml is readable "/Users/jpaton/.okta/okta.yaml"
okta.yaml is valid yaml
okta.yaml has root "awscli" section
okta.yaml "awscli.idps" section is a map of 7 ARN string keys to friendly string label values
okta.yaml is OK
debugging okta-aws-cli config $HOME/.okta/okta.yaml is **complete**

$ okta-aws-cli login --org-domain okta.company.com --oidc-client-id ${THE_ID} --aws-acct-fed-app-id ${THE_OTHER_ID}
Open the following URL to begin Okta device authorization for the AWS CLI

https://okta.$company.com/activate?user_code=ABCDEFGH

? Choose an IdP:  [Use arrows to move, type to filter]
> arn:aws:iam::012345678910:saml-provider/company-okta-idp
  arn:aws:iam::123456789100:saml-provider/company-okta-idp
  arn:aws:iam::234567891001:saml-provider/company-okta-idp

[ etc etc ]
```

And my friendly name config is

```yaml
# ~/.okta/okta.yaml
---
awscli:
  idps:
    "arn:aws:iam::012345678910:saml-provider/company-okta-idp": friendly-name-1
    "arn:aws:iam::123456789100:saml-provider/company-okta-idp": friendly-name-2
    "arn:aws:iam::234567891001:saml-provider/company-okta-idp": friendly-name-3

# etc etc
```

**Comment by monde** [comment]
I've released https://github.com/okta/okta-aws-cli/releases/tag/v1.2.0 which is available via homebrew (`brew update && brew upgrade okta-aws-cli` and it support friendly labels for Role ARNs. e.g.:
```yaml
---
awscli:
  idps:
    "arn:aws:iam::123456789012:saml-provider/company-okta-idp": "Data Production"
    "arn:aws:iam::012345678901:saml-provider/company-okta-idp": "Data Development"
    "arn:aws:iam::901234567890:saml-provider/company-okta-idp": "Marketing Production"
    "arn:aws:iam::890123456789:saml-provider/company-okta-idp": "Marketing Development"
  roles:
    "arn:aws:iam::123456789012:role/admin": "Prod Admin"
    "arn:aws:iam::123456789012:role/operator": "Prod Ops"
    "arn:aws:iam::012345678901:role/admin": "Dev Admin"
    "arn:aws:iam::012345678901:role/operator": "Dev Ops"
```

Use `okta-aws-cli --debug-config` for diagnostic information about your okta.yaml. This is a standalone command that runs and exits.

Use `--debug` where okta-aws-cli will print diagnostic information about okta.yaml and the ARNs it is seeing while requesting AWS creds e.g. `okta-aws-cli --oidc-client-id [app id] --org-domain [org domain] --open-browser --debug`

**Comment by kenhen93Evolve** [comment]
@monde I have tested your new code and it works! I would say my only feedback is to not show the ARN too.

 Choose an IdP:  [Use arrows to move, type to filter]
   DevOps (arn:aws:iam::999999999:saml-provider/okta)
  Sandbox (arn:aws:iam::999999999:saml-provider/okta)

Choose a Role:  [Use arrows to move, type to filter]
> DevOps Admin (arn:aws:iam::999999999999:role/admin)

Thank you very much!

**Comment by monde** [comment]
I can clean that up @kenhen93Evolve

**Comment by joshgch** [comment]
@monde I can confirm that friendly names work for my org with 1.2.0. Thank you!

I tested and cannot use these friendly names with the `-i` and `-r` arguments. Should I create a new feature request for this, or can you add this capability?

**Comment by kenhen93Evolve** [comment]
@monde The IDP looks good now but the role still shows the arn.

 Choose an IdP: DevOps
? Choose a Role: arn:aws:iam::000000000:role/poweruser

Thanks for that though. Looks better. Maybe we can do the role name too?

**Comment by monde** [comment]
@kenhen93Evolve double check you are running v1.2.1 and run your command with `--debug`. You'll get debug information about what okta-aws-cli is seeing in the okta.yaml when it is looking up friendly labels for a given ARN value. This done for both IdP and Role label lookup. As shown in my screen grab https://github.com/okta/okta-aws-cli/issues/102#issuecomment-1680931970 the "S3 Read/Write" Role friendly label is being looked up in my okta.yaml

**Comment by kenhen93Evolve** [comment]
@monde I had the right version but didn't config the role name in my okta.yaml. Once I did, it did work. Thank you!!!!

**Comment by joshgch** [comment]
> @joshgch I double checked the [okta-aws-cli](https://oktainc.atlassian.net/browse/OKTA-aws-cli) v1.2.1 installed by brew on my localhost and the long `--aws-iam-idp` and `--aws-iam-role` flags and short `-i` and `-r` flags are operating correctly for me. Can you double check that you have v1.2.1 installed? See my screen grab: ![Screenshot_2023-08-16_at_9_21_30_AM](https://user-images.githubusercontent.com/201/261076311-29a12606-1463-4dfd-81e1-f203270eeac3.png)

Hi @monde,

I can confirm that I can still invoke the command as expected with those arguments if I put in the full ARN. My question/suggestion was whether a feature could be added to support logging in using the friendly names in the arguments instead.

example:
```shell
okta-aws-cli -i friendly-account-name -r friendly-role-name
````

**Comment by monde** [comment]
@joshgch got it, I see your ask, thanks for the clarification.
